# Generated by Django 4.1.7 on 2023-05-05 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("consumer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="consumerBilling",
            fields=[
                (
                    "consumer_det",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="consumer.consumer",
                    ),
                ),
                ("invoice_id", models.IntegerField()),
                ("previous_unit", models.CharField(max_length=50)),
                ("current_unit", models.CharField(max_length=50)),
                ("amount", models.CharField(max_length=50)),
                ("date", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=50)),
            ],
        ),
    ]
