# Generated by Django 4.1.7 on 2023-05-04 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0007_rename_consumer_consumer_profile_phone'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerbilling',
            name='consumer_id',
        ),
        migrations.RemoveField(
            model_name='consumerbilling',
            name='consumer_name',
        ),
        migrations.RemoveField(
            model_name='consumerbilling',
            name='meter_number',
        ),
        migrations.AddField(
            model_name='consumerbilling',
            name='consumer_det',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consumer.consumer'),
        ),
    ]
