# Generated by Django 4.1.7 on 2023-05-05 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerbilling',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consumerbilling',
            name='consumer_det',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='consumer.consumer'),
        ),
    ]
