# Generated by Django 4.1.7 on 2023-05-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_consumerbilling_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerbilling',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
