# Generated by Django 4.1.7 on 2023-05-04 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0007_rename_consumer_consumer_profile_phone'),
        ('billing', '0002_remove_consumerbilling_consumer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerbilling',
            name='id',
        ),
        migrations.AlterField(
            model_name='consumerbilling',
            name='consumer_det',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='consumer.consumer'),
        ),
    ]
