# Generated by Django 4.1.7 on 2023-05-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_consumerbilling_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerbilling',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
