# Generated by Django 4.1.7 on 2023-05-05 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0002_rename_consumerobj_consumer_profile_consumer'),
        ('billing', '0004_alter_consumerbilling_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerbilling',
            name='consumer_det',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='consumer.consumer'),
        ),
    ]
