# Generated by Django 4.1.7 on 2023-05-05 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consumer",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("consumer_id", models.IntegerField()),
                ("name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=50)),
                ("meter_no", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("citizenship", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Consumer_Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.IntegerField()),
                ("password", models.CharField(max_length=50)),
                (
                    "consumerobj",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consumer.consumer",
                    ),
                ),
            ],
        ),
    ]
