# Generated by Django 4.1.7 on 2023-03-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('consumer_id', models.IntegerField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('meter_no', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('citizenship', models.CharField(max_length=50)),
            ],
        ),
    ]
