# Generated by Django 4.1.7 on 2023-03-28 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0002_consumer_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumer_profile',
            old_name='consumer',
            new_name='consumerobj',
        ),
    ]
