# Generated by Django 4.1.7 on 2023-05-07 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0003_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='PasswordProfile',
        ),
    ]
