# Generated by Django 4.1.7 on 2023-05-07 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0004_rename_profile_passwordprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='consumer.consumer_profile'),
        ),
    ]
