# Generated by Django 4.1.7 on 2023-03-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0004_remove_consumer_profile_consumerobj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='consumer_id',
        ),
        migrations.AlterField(
            model_name='consumer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
