# Generated by Django 4.1.7 on 2023-05-07 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0005_alter_passwordprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='consumer.consumer'),
        ),
    ]
