# Generated by Django 4.1.7 on 2023-03-28 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0006_consumer_consumer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumer_profile',
            old_name='consumer',
            new_name='phone',
        ),
    ]
